dist: trusty
language: android
jdk: oraclejdk8

licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

addons:
  apt:
    # Flutter dependencies
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-noto

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - build-tools-27.0.3
    - android-27
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-android-support

before_install:
  - echo $TRAVIS_OS_NAME
  - echo ${HOME}
  - echo ${TRAVIS_BUILD_DIR}
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager ndk-bundle
  - git clone https://github.com/flutter/flutter.git -b stable ${HOME}/flutter
  - ${HOME}/flutter/bin/flutter doctor -v
  - ${HOME}/flutter/bin/flutter packages get

script:
  - ${HOME}/flutter/bin/flutter test

after_success:
  - echo "success"

after_failure:
  - echo "failure"
