os: linux
language: dart

addons:
  apt:
    # Flutter dependencies
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6

before_install:
  - echo $TRAVIS_OS_NAME
  - echo ${HOME}
  - echo ${TRAVIS_BUILD_DIR}
  - sudo apt-get install lib32stdc++6
  - git clone https://github.com/flutter/flutter.git -b stable ${HOME}/flutter
  - ${HOME}/flutter/bin/flutter doctor -v
  - ${HOME}/flutter/bin/flutter packages get

script:
  - ${HOME}/flutter/bin/flutter test

after_success:
  - echo "success"

after_failure:
  - echo "failure"
