name: cruzawl_ui
description: Flutter package for the CRUZ cryptocurrency and the cruzbit.1 network.

version: 1.0.0+0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  barcode_scan: ^1.0.0
  charts_flutter: ^0.8.0
  cruzawl:
    path: ../cruzawl
  json_annotation: ^3.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  gradient_app_bar: ^0.0.1
  qr_flutter:
    git:
      url: git://github.com/lukef/qr.flutter.git
  sembast: ^2.0.1
  scoped_model: ^1.0.1
  syntax_highlighter: ^0.1.0
  tuple: ^1.0.2
  tweetnacl: ^0.3.2

dev_dependencies:
  build_runner: ^1.4.0
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.1
  json_serializable: ^3.2.0

dependency_overrides:
  intl: 0.16.0

flutter:
  uses-material-design: true
  assets:
    - assets/
