name: cruzawl_ui
description: Flutter submodule for CRUZ cryptocurrency.

version: 1.0.0+0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  barcode_scan: ^1.0.0
  charts_flutter: ^0.6.0
  cruzawl:
    git:
      url: git://github.com/GreenAppers/cruzawl.git
  json_annotation: ^3.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  gradient_app_bar: ^0.0.1
  qr_flutter:
    git:
      url: git://github.com/lukef/qr.flutter.git
  sembast: ^2.0.1
  scoped_model: ^1.0.1
  tweetnacl: ^0.3.2

dev_dependencies:
  build_runner: ^1.4.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
