name: cruzawl_ui
version: 1.0.0+0
description: Flutter package for the CRUZ cryptocurrency and the cruzbit.1 network.
author: Green Appers, Inc. <greenappers@gmail.com>
homepage: https://github.com/GreenAppers/cruzawl-ui

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  barcode_scan: ^1.0.0
  bip39: ^1.0.3
  charts_flutter: ^0.8.1
  collection: ^1.14.11
  cruzawl:
    path: ../cruzawl
  json_annotation: ^3.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  gradient_app_bar: ^0.0.1
  intl: any
  pedantic: ^1.8.0
  qr_flutter: ^3.0.1
  sembast: ^2.0.1
  scoped_model: ^1.0.1
  syntax_highlighter: ^0.1.0
  tuple: ^1.0.2
  tweetnacl:
    git:
      url: https://github.com/GreenAppers/tweetnacl-dart

dev_dependencies:
  build_runner: ^1.4.0
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.1
  json_serializable: ^3.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
